"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from vault12factor import (
    VaultAuth12Factor,
    VaultCredentialProvider,
    DjangoAutoRefreshDBCredentialsDict,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-sq&rhnj@@i10x7&6peaubpdvymu%5-lsr-!7lz-l9ke4$1o^cm"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1")

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", default="").split(" ")
# ALLOWED_HOSTS = ["chat.api.transcendence.fr", "transcendence.fr"]

# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "channels",
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_dbconn_retry",
    "health_check",
    "health_check.db",
    "livechat",
    "postgresql_setrole",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "vault12factor",
]

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",  # Permet l'interface de navigation
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "https://transcendence.fr",
    "https://www.transcendence.fr",  # If subdomains are needed
]

CSRF_TRUSTED_ORIGINS = ["https://transcendence.fr"]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Daphne
ASGI_APPLICATION = "core.asgi.application"

VAULT = VaultAuth12Factor.fromenv()
CREDS = VaultCredentialProvider(
    os.getenv("VAULT_ADDR"),
    VAULT,
    "database/creds/chat",
    os.getenv("VAULT_CACERT", None),
    True,
    DEBUG,
)

RMQ_CREDS = VaultCredentialProvider(
    os.getenv("VAULT_ADDR"),
    VAULT,
    "rabbitmq/creds/chat",
    os.getenv("VAULT_CACERT", None),
    True,
    DEBUG,
)

RMQ_ADDR = f"amqp://{RMQ_CREDS.username}:{RMQ_CREDS.password}@{os.getenv("RMQ_ADDR")}"
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": DjangoAutoRefreshDBCredentialsDict(
        CREDS,
        {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "chat",
            "USER": CREDS.username,
            "PASSWORD": CREDS.password,
            "HOST": "chat-db",
            "PORT": "5432",
            "SET_ROLE": "owner",
        },
    ),
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "livechat.ChatUser"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "/static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
