# syntax=docker/dockerfile:1

FROM node:23-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN mkdir /app
COPY ./static/package.json /app
COPY ./static/pnpm-lock.yaml /app
WORKDIR /app

FROM base AS deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM base
COPY --from=deps /app/node_modules /app/node_modules
CMD ["pnpm", "exec", "vite", "build", "-w"]