# Generated by Django 5.1.1 on 2024-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
